name: pomodoromanuscriptapp
description: "Aplicación de Pomodoro con temporizadores configurables, seguimiento de estadísticas y una estética de manuscrito en papel beige."
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
